[package]
name = "powershenn"
version = "0.1.0"
edition = "2021"

[dependencies]
fltk = "1.4"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"

[[bin]]
name = "powershenn"
path = "main.rs"